name=M5PicomniRover
version=0.1.1
author=Rin Iwai
maintainer=Rin Iwai <me@eyrin.jp>
sentence=Library for M5PicomniRover omni-wheel robot
paragraph=Provides motor control, BLE, and example sketches.
category=Device Control
url=https://github.com/tutrc-b1/M5PicomniRover_Arduino
architectures=esp32
depends=NimBLE-Arduino
includes=M5PicomniRover.h
