name=M5StampRover
version=0.1.0
author=Rin Iwai
maintainer=Rin Iwai <me@eyrin.jp>
sentence=Library for M5StampRover omni-wheel robot
paragraph=Provides motor control, BLE, and example sketches.
category=Device Control
url=https://github.com/tutrc-b1/M5StampRover_Arduino
architectures=esp32
depends=NimBLE-Arduino
includes=M5StampRover.h
